### ISSUE TITLE
Please Release Version: 2.13.3

### ISSUE THREAD

**Issue by james-hu** [webjars/salesforce-lightning-design-system#2]

**Comment by jamesward** [comment]
I see that `2.13.6` is on GitHub: https://github.com/salesforce-ux/design-system/tags
But that release is not available where we get our releases from:
https://www.lightningdesignsystem.com/resources/downloads/

Can you file a GitHub issue to see if they can fix that?

**Comment by james-hu** [comment]
Sorry I didn't check the download page. I saw 2.13.3 is the latest on that page, could you release that version?
BTW, previously I thought the release is automatic by a bot. Thank you for maintaining these versions!
